### ISSUE TITLE
Format for jasmineExplorer.config?

### ISSUE THREAD

**Issue by ardalis** [hbenl/vscode-jasmine-test-adapter#1]
I'm definitely interested in using this extension but it needs some more docs or at least a better readme. Is jasmineExplorer.config a JSON file or does it just have a single line with the path to jasmine.conf or what?

Also, I'm using Angular and Karma and I don't have a jasmine.conf file. I just have karma.conf.js. Will that work with this?

Thanks!

**Comment by hbenl** [comment]
This is the standard jasmine configuration file as described [here](https://jasmine.github.io/setup/nodejs.html#configuration).
I haven't looked into Angular and Karma yet, so I don't know if and how that could work with this test adapter (or if a separate karma test adapter would be needed). I want to look into this eventually, but that's just one item on a long list of TODOs for me, so it might take a while (unless someone steps up and contributes the necessary code and/or documentation ;) )

**Comment by ardalis** [comment]
Understood. Thanks and good luck!
