### ISSUE TITLE
Test Explorer window not showing Jasmine tests

### ISSUE THREAD

**Issue by MrClyfar** [hbenl/vscode-jasmine-test-adapter#12]
I'm using `VS Code 1.24.1` with `Jasmine Test Explorer v0.8.0`

To experiment with this extension, I opened the following project in VS Code.

https://github.com/Krafty-Coder/jasmine-test-practice

I installed jasmine using npm.

The Test Explorer window does not find any tests. Neither does the code lens Run/Debug functionality appear in any of the spec files. When I open the `SpecRunner.html` file that is part of the project, the test output is generated without any problems. So it looks like jasmine is up and running correctly.

Other than installing the extension, is there something else I need to do in order for it to pick up the tests?

**Comment by hbenl** [comment]
You can see Jasmine's output in a VS Code output channel (this isn't documented yet):
![screenshot_2018-07-06_13-28-57](https://user-images.githubusercontent.com/16060807/42377166-6a2fc090-8122-11e8-822c-c0b5cecbe6c9.png)

That pointed me to several problems in the project:
* the file `spec/totest.spec.js` is syntactically incorrect. The configuration tells jasmine to include that file, which causes it to fail
* the configuration `spec/support/jasmine.json` configures jasmine differently from what `SpecRunner.html` does. I guess it should be more like this:
```
{
  "spec_dir": "spec",
  "spec_files": [
    "testlogin.spec.js"
  ],
  "helpers": [
    "../src/user_library.js"
  ],
  "stopSpecOnExpectationFailure": false,
  "random": true
}
```
* with the fixed configuration I can load the tests, but when I run them, they all fail. I set breakpoints at the start of `user_library.js` and in the `beforeEach` function in `testlogin.spec.js` and debugged one of the tests. That showed me that `user_library.js` is run, but the `User` constructor is not available in the context of the test file. I guess that has to do with how jasmine handles the "helpers". Anyway, the tests also fail when I run jasmine on the command line, so this is not a bug in this extension.

**Comment by MrClyfar** [comment]
Awesome, thanks for taking the time to help. I'm new to using Jasmine, so your input has helped a lot for me.

Many thanks.

**Comment by danilaml** [comment]
I don't see `Jasmine Tests` in `output`. Is this normal? Also, does it work with .yml jasmine config?
