### ISSUE TITLE
Does not work for TypeScript based projects

### ISSUE THREAD

**Issue by infoneershalin** [hbenl/vscode-jasmine-test-adapter#13]
I am not able to see Tests written in TypeScript.
Is there any way we can see TypeScript based tests and execute them?

**Comment by hbenl** [comment]
If you are able to execute them on the command line, they should also work with this test adapter.
Please add your `jasmine.json`, the configuration for this extension (if you have any) and the content of the diagnostic log (as described in the [Troubleshooting](https://github.com/hbenl/vscode-jasmine-test-adapter#troubleshooting) section).

**Comment by infoneershalin** [comment]
log says

`Randomized with seed 85617
Started


No specs found
Finished in 0.006 seconds
Incomplete: No specs found
Randomized with seed 85617 (jasmine --random=true --seed=85617)
`

and here is my jasmine.json

`{
	"spec_dir": "spec",
	"spec_files": [
	  "**/*[sS]pec.js","**/**/*[sS]pec.js"
	],
	"helpers": [
	]
  }
`

basically I have .ts files which is like below

`import { browser } from 'protractor';
import { HomePage } from '../../pages/home_page';

describe('Home Page', () => {
  const homePage = new HomePage();

  beforeEach(() => {
    homePage.acceptTerms();
  });

  it('should have the correct elements', () => {
    // TODO: Fill out this spec!
    browser.get(browser.params.baseUrl);
    // browser.wait(ExpectedConditions.presenceOf(homePage.getHeader()), 2000);
    // expect(homePage.getHeader().isPresent()).toBe(true);
  });
});`


For executing this from command line I am using `npm run test` and the scripts of my package.json is like below

`"scripts": {
    "prepare": "node_modules/.bin/webdriver-manager update",
    "update": "node_modules/.bin/webdriver-manager update",
    "test": "node_modules/.bin/protractor tmp/config.js",
    "debug": "node --inspect --debug-brk ./node_modules/.bin/protractor tmp/conf.js",
    "tsc": "tsc",
    "pretest": "tsc",
    "test-qa": "npm run test",
    "pretest-prod": "tsc",
    "test-prod": "protractor tmp/conf.js --params.baseUrl=https://www.google.com"
  }`

**Comment by hbenl** [comment]
Sorry, this adapter doesn't work with protractor. Basically it can only work with tests that are run when you call `jasmine` directly on the command line. But in your case you need to call `protractor` on the command line, which then calls `jasmine`.
