### ISSUE TITLE
Support for Javascript source maps

### ISSUE THREAD

**Issue by wduminy** [hbenl/vscode-jasmine-test-adapter#14]
It would be nice if this extension can follow [Javascript source maps](https://www.html5rocks.com/en/tutorials/developertools/sourcemaps/) to click through and debug non javascript source files.

**Comment by hbenl** [comment]
This is already possible using e.g. `ts-node/register` or `babel-register` - these will transpile the source files on-the-fly during testing and also modify the stacktraces so that they show the original source code positions (at least `ts-node` does, I haven't checked `babel-register`).

**Comment by wduminy** [comment]
I will look into that.  Thank you.
