### ISSUE TITLE
 Incompatible with VS Code '1.20.0'.

### ISSUE THREAD

**Issue by gtcdevop** [hbenl/vscode-jasmine-test-adapter#16]
Unable to install 'hbenl.vscode-jasmine-test-adapter'; there is no available version compatible with VS Code '1.20.0'.

![screen shot 2018-08-24 at 13 42 39](https://user-images.githubusercontent.com/28716084/44596710-9ec4b700-a7a3-11e8-801a-5465eda12f42.png)

**Comment by gtcdevop** [comment]
@hbenl @flovilmart, is this expected?

**Comment by flovilmart** [comment]
I'm running with vscode 1.26.1, and it works as expected. Please update your version of vscode.

**Comment by gtcdevop** [comment]
It worked! Thanks !!
