### ISSUE TITLE
How to use this for angular-cli projects?

### ISSUE THREAD

**Issue by manojp1988** [hbenl/vscode-jasmine-test-adapter#17]
I'm developing angular application with the folder structure created by angular cli. I installed this extension, but tests are not loading in the explorer. Do I need to do anything specific for angular/typescript?

**Comment by hbenl** [comment]
angular-cli projects use Karma and Protractor for their tests. Even though both use Jasmine behind the scenes, they are incompatible with this Test Adapter and would require their own Test Adapters.

**Comment by hbenl** [comment]
A Karma adapter is being worked on, see hbenl/vscode-example-test-adapter#1
