### ISSUE TITLE
Unable to load unit tests

### ISSUE THREAD

**Issue by chadcampbell** [hbenl/vscode-jasmine-test-adapter#2]
Hello,

This extension looks like its just what I've been looking for. However, I've been unsuccessful in getting the extension to work. Here is my setup:

- Downloaded the extension into Visual Studio Code (version 1.23.1)
- Initialized Jasmine tests for Node.js via `node jasmine init`. This created a directory named 'spec'. Included in this directory was another directory named 'support' with a file named 'jasmine.json' in it.
- I added a file named tests.spec.js into the 'spec' directory. That file looks like this:

```
describe("A suite", function() {
    it("contains spec with an expectation", function() {
      console.log('running test');
      expect(true).toBe(true);
    });
  });
```

- I visited the "Test" extension tab in the far left column of Visual Studio Code. However, there is nothing visible in the "TEST: TEST EXPLORER" pane.

What am I missing?

Thank for putting this extension together.

**Comment by hbenl** [comment]
Thanks for the detailed bug report. Have you tried hitting the reload button in the Test Explorer pane? The extension doesn't automatically reload the tests yet.
If that doesn't help, please tell me what operating system you're on.

**Comment by chadcampbell** [comment]
I did hit the reload button in the Test Explorer pane. However, nothing ever got loaded. The mouse cursor changed to the wait indicator for a moment. However, I never saw any tests appear. I waited for ~3 minutes.

I'm running Visual Studio Code on Windows 10.

**Comment by hbenl** [comment]
Thanks, I found the bug and published a fixed version.
