### ISSUE TITLE
Need help in making this work with RequireJS

### ISSUE THREAD

**Issue by kat3samsin** [hbenl/vscode-jasmine-test-adapter#27]
Thank you for making this plugin. I am using RequireJS in my project I always get  'ReferenceError: define is not defined'. I would greatly appreciate any help. Thanks.

**Comment by hbenl** [comment]
Sorry, I have no experience with RequireJS. Furthermore, this issue seems to be about writing Jasmine tests in general and is not specific to this extension, so I'm closing it. You should open a corresponding issue in the Jasmine issue tracker.
