### ISSUE TITLE
document is not defined

### ISSUE THREAD

**Issue by kambizalipour** [hbenl/vscode-jasmine-test-adapter#29]
I have an Angular 7 CLI project with 700+ tests and all are passing using ng test command.
I tried Jasmine Test Explorer 1.4.1 and getting the following error in the log:
```
'function' === typeof document.createEvent ? function CustomEvent (type, params) {
                      ^
ReferenceError: document is not defined
```
Any thoughts of what I'm missing here?

I'm using VS Code 1.30.2 on Windows 10

**Comment by hbenl** [comment]
angular-cli projects use Karma and Protractor for their tests. Even though both use Jasmine behind the scenes, they are incompatible with this Test Adapter and would require their own Test Adapters.
See also #17 and hbenl/vscode-test-explorer#19.

**Comment by hbenl** [comment]
A Karma adapter is being worked on, see hbenl/vscode-example-test-adapter#1
