### ISSUE TITLE
[help] Jasmine config is in Karma

### ISSUE THREAD

**Issue by acronamy** [hbenl/vscode-jasmine-test-adapter#30]
I am trying to find a way to get this beast working, but I cannot refactor our codebase. Can vscode-jasmine-test-adapter read Karma configs. or perhaps I can store my own spoof jasmine.json in my home folder. How would I be able to point to this config? I notice that only relative paths are supported.

**Comment by hbenl** [comment]
This adapter can't load and run Karma tests, but a Karma adapter is being worked on, see hbenl/vscode-example-test-adapter#1
