### ISSUE TITLE
Not fully understanding how to setup

### ISSUE THREAD

**Issue by alexandercerutti** [hbenl/vscode-jasmine-test-adapter#32]
Hi, I've created tests on Jasmine in folder structure like `<project>/tests/index.js` (I've no other files).
I've found this extension but it cannot find my tests (while, if I run through CLI, Jasmine can find them). I tried to read the documentation and the other issues but nothing, and to me it is not that clear how to begin.
Moreover, I tried to create a configuration in launch.json, and vscode says that options that start with `jasmineExplorer` are not supported.
I'm using WSL (Bash on Windows), I don't know if this may help.
If I try to start debugging, it is not able to connect. If I try to remove the port and use "launch" instead of "attach" and `"useWSL": true`, it starts but does not anything.

Jasmine is installed as module package (and, I don't know, maybe also globally, but I'm not sure)
Extension version: 1.4.2 (jasmine test adapter, 2.8.2 Test UI adapter)

Thank you for the help.

**Comment by hbenl** [comment]
* this extension expects a jasmine configuration file in `spec/support/jasmine.json`. Simply run `jasmine init` to create it and then adapt it to your setup. You should be able to run your tests by calling `jasmine` without any arguments on the command line.
* configuration options must be added to `.vscode/settings.json`, not to `.vscode/launch.json`. However, in most setups, you shouldn't need any configuration options (the options in `jasmine.json` should be sufficient)
* you probably don't need any configuration in `.vscode/launch.json` to run and debug your tests using this extension

**Comment by alexandercerutti** [comment]
Thank you very much!! That was not clear!
