### ISSUE TITLE
command 'test-explorer.run-all' not found

### ISSUE THREAD

**Issue by bremner** [hbenl/vscode-jasmine-test-adapter#4]
Perhaps I'm missing a mandatory configuration step, but:

1) I have installed Test Explorer 0.4.1 and Jasmine Test Explorer 0.5.1
2) The icon shows up, and the test view starts, but when I click, e.g. "play", I get the error message in the subject.

**Comment by hbenl** [comment]
That is very weird. The error message indicates that the Test Explorer extension hasn't been initialized (otherwise the command would be found), but the "play" icon wouldn't be there if the extension wasn't initialized... in other words: no matter how you configured it, this should not happen.
I can't reproduce this (and can't think of how this is even possible), so I can only advise to experiment some more, possibly with a fresh install of VS Code with no other extensions.

**Comment by hbenl** [comment]
> [...] but I also don't get any output from e.g. a failing jasmine test.

So does that mean that the Test Explorer stays empty (i.e. the extension doesn't show the list of tests)?

Anyway I'll be adding a logging facility to this extension soon, that may help tracking down this issue.

**Comment by bremner** [comment]
Holger Benl <notifications@github.com> writes:

>> [...] but I also don't get any output from e.g. a failing jasmine test.
>
> So does that mean that the Test Explorer stays empty (i.e. the extension doesn't show the list of tests)?

Correct.

>
> Anyway I'll be adding a logging facility to this extension soon, that may help tracking down this issue.
>

Sounds good.

**Comment by alimbada** [comment]
I think I have a similar issue. I have installed the extension and restarted VSCode, but my tests are not detected, i.e. the Test Explorer view is empty. However, I do not have any errors when clicking the play button.

I'm using the official VSCode build on Windows.

**Comment by hbenl** [comment]
The extension now forwards the jasmine console output to a VS Code output channel (this feature isn't documented yet): Have a look at the Output panel at the bottom of VS Code. After trying to load the tests, the dropdown should offer a channel "Jasmine Tests", which may help understanding why the tests aren't loaded.

**Comment by alimbada** [comment]
@hbenl I've updated the extension, but I'm not seeing the a "Jasmine Tests" output channel.

**Comment by hbenl** [comment]
@alimbada The output channel only shows up after you have switched to the Test view.
![screenshot_2018-07-09_18-19-23](https://user-images.githubusercontent.com/16060807/42462929-fe2c2ec6-83a4-11e8-985a-1c9bbc9e7a84.png)

**Comment by hbenl** [comment]
If it doesn't show up even after switching to the Test view, it could mean that the adapter
* can't find your jasmine config file
* can't parse it
* can't find any test files referenced by that config file
* can't start the worker that loads the tests

If you can run your tests by calling "jasmine" on the command line in your project folder, then that should rule out the first 3 possibilities. In that case, try setting `jasmineExplorer.nodePath` to `null` and see if that makes any difference.

**Comment by alimbada** [comment]
Currently I am using karma to run the tests outside of VS so I don't have a jasmine.config file. I only have karma config files. I'm guessing that's the issue.

**Comment by hbenl** [comment]
> I don't have a jasmine.config file. I only have karma config files. I'm guessing that's the issue.

Yes, that explains it.

**Comment by bremner** [comment]
Holger Benl <notifications@github.com> writes:

> Closed #4.
>

I do have a jasmine config and jasmine works fine from the command line.

**Comment by hbenl** [comment]
@bremner I've just published a new version that contains options for diagnostic logging (described in the [Troubleshooting](https://github.com/hbenl/vscode-jasmine-test-adapter#troubleshooting) section), please try again with that version and attach the logs.

**Comment by bremner** [comment]
Holger Benl <notifications@github.com> writes:

> @bremner I've just published a new version that contains options for diagnostic logging (described in the [Troubleshooting](https://github.com/hbenl/vscode-jasmine-test-adapter#troubleshooting) section), please try again with that version and attach the logs.
>

Apologies for the long delay.

I feel like I must be missing something fundamental.  I set the config
for the log file (which autocompleted in the config editor, so I guess
were known) but I don't see an output file. Similarly, I don't see a
"Jasmine Explorer Log" if I set that config to true.

**Comment by hbenl** [comment]
> I have attached the extension host log

I can't find it, I guess Github doesn't support Email attachments.

**Comment by bremner** [comment]
A pity about email attachements. Here it is.

[exthost1.log](https://github.com/hbenl/vscode-jasmine-test-adapter/files/2217435/exthost1.log)

**Comment by hbenl** [comment]
That's what I expected: the extensions don't get started, something seems to be wrong with your installation of VS Code (although I have no idea what that could be).
