### ISSUE TITLE
Performance

### ISSUE THREAD

**Issue by flovilmart** [hbenl/vscode-jasmine-test-adapter#5]
Hi there! Awesome project you have there, I was looking for one for parse-server for a while.

We have more that 1000 tests and running with babel register, the stategy to parse every single files one after the other is quite slow, and il takes about a 2 minutes to load all the tests.

I've come up with a workaround, involving monkey patching the `it` method and looking at the stacktrace for determine the caller location in file.

Is this a change you'd like to pull in?

Thanks!

**Comment by hbenl** [comment]
Yes, that sounds very interesting! I would keep the current method as well and let the user choose (because each method may not work reliably under some circumstances), but this could become the new default.

**Comment by flovilmart** [comment]
Alright, I'll do my best to provide a clean way to make both live togeteher :)

**Comment by hbenl** [comment]
Fixed in #11
