### ISSUE TITLE
Bump jasmine version or use the workspace version

### ISSUE THREAD

**Issue by vsDizzy** [hbenl/vscode-jasmine-test-adapter#50]
Currently referenced Jasmine version 3.6.3 is missing "jsLoader" configuration option. So I'm having troubles running tests with ts-node and type=module in package.json.
Please bump Jasmine version to 4.0.2 or even allow to use Jasmine from the workspace packages.

**Comment by hbenl** [comment]
I've released a new version that includes Jasmine 4.0.2.

> or even allow to use Jasmine from the workspace packages.

That was already possible: https://github.com/hbenl/vscode-jasmine-test-adapter/blob/d6c4a5d23e8af3755bebfb42ef220a18e03122a1/README.md?plain=1#L61
