### ISSUE TITLE
New release `v1.7.2` breaks test explorer UI

### ISSUE THREAD

**Issue by omairvaiyani** [hbenl/vscode-jasmine-test-adapter#52]
We were unable to see any of our tests inside the Test Explorer UI. We cannot see any error messages when looking at the `Jasmine Tests` nor `Test Explorer` output. Switching this addon version to `v.1.7.1` resolves the issue.

I noticed that you've upgraded to Jasmine `v4` for this plugin - is that a breaking change? We're currently on Jasmine `v3.6.10`.

Thanks!

**Comment by hbenl** [comment]
I didn't think jasmine v4 was a breaking change, but I'm not an expert on jasmine. Have you tried running your tests on the command line with jasmine v4?
In any case, you can always tell the extension to use the version of jasmine installed in your workspace by adding `"jasmineExplorer.jasminePath": "node_modules/jasmine"` to your settings.

**Comment by omairvaiyani** [comment]
Turns out it was related to how we injected a custom reporter - we were clearing the default reports which likely disables the Test Runner.
