### ISSUE TITLE
Upgrade to Jasmine 4.0 broke tests unexpectedly

### ISSUE THREAD

**Issue by twasink** [hbenl/vscode-jasmine-test-adapter#54]
The recent upgrade to bundling Jasmine 4.0 broke a bunch of my tests recently. The fix was straight-forward - I specified the `jasminePath` as described in the documentation. But diagnosing that was the cause was a real pain, especially as tests were running just fine on the CLI; it wasn't remotely clear that the Jasmine version had changed.

Perhaps the extension should _default_ to using `node_modules/jasmine`, only falling back to the bundled version if that's not present?

**Comment by twasink** [comment]
Note that I'm not surprised the upgrade broke stuff; the Jasmine project indicates that there are breaking changes between 3.x and 4.x. I was just surprised that it was happening inside my IDE and not on the CLI.

**Comment by hbenl** [comment]
> Perhaps the extension should default to using `node_modules/jasmine`

You're right, starting with version 1.8.0 it does so.
