### ISSUE TITLE
Windows: running a large number of tests does nothing (all remain pending)

### ISSUE THREAD

**Issue by danmana** [hbenl/vscode-jasmine-test-adapter#58]
If I have a large project with hundreds of tests, clicking on the `Run all` button does not run the tests.
The status of all tests is set to `pending` but the `runTests` worker thread never starts, so it gets stuck in this pending state.

The same happens if I select just half of the tests and run them.
However, running a few tests at a time works.

After debugging a bit, it turns out that `child_process.fork` does not start a process when one of the args is very large - in our case, it contains a `JSON.stringify(allTestNames)` (googling a bit shows the limit at [8191 chars?!](https://docs.microsoft.com/en-us/troubleshoot/windows-client/shell-experience/command-line-string-limitation#:~:text=The%20maximum%20length%20of%20the,such%20as%20the%20PATH%20variable))

I made a new PR to fix this by sending the list of tests as a subprocess message, which is not limited.
With the new change, I can run all 400+ tests on Windows.

**Comment by hbenl** [comment]
Fixed in version 1.8.0.
